### ISSUE TITLE
Workrave sponsorship

### ISSUE THREAD

**Issue by tjkirch** [rcaelers/workrave#142]
**Describe the bug**
Workrave is an invaluable tool and helps keep me healthy.  I'd like to help sponsor development somehow.

**To Reproduce**
1. Enjoy Workrave
2. Search for ways to help sponsor development
3. Find no ways

**Expected behavior**
Find a Patreon, [GitHub Sponsors](https://github.com/sponsors), etc.

**Screenshots**
<you probably don't want a picture of my arm tendons>

**Additional context**
Thank you!

**Comment by nkomarov** [comment]
Experience the same on my computer. Being unable to sponsor makes my user experience not so perfect.

**Comment by rcaelers** [comment]
Thanks for your kinds words :-) It's always good to hear that people like Workrave. 

This is what we put in our FAQ several years ago (currently badly formatted on the Workrave website...): 

"I am glad that you like our software. We appreciate any donations, however, we prefer donations on a meta-level. Meaning, instead of donating directly to us, free software authors, we feel it is a better idea to donate to a foundation that ensures that the conditions amongst which free software can flourish remain valid. Therefore, I would like you to donate to the Electronic Frontier Foundation directly. Please visit [EFF](https://www.eff.org/) – you’ll find paypal (a.o.) links there."
