### ISSUE TITLE
Branch `next` points to outdated commit.

### ISSUE THREAD

**Issue by kindaro** [rcaelers/workrave#143]
**Describe the bug**

Branch `next` points to outdated commit. It is several commits behind the release `branch_v1_10` and those commits actually fix important bugs.

We Arch Linux people have [this package in AUR][1] that makes a build from the `next` branch. Either we should remove it or maybe the maintainers could just set `next` to point to the most recent actual commit, like maybe `branch_v1_10`.

[1]: https://aur.archlinux.org/packages/workrave-next-gtk3-git

If `next` is not used anymore, maybe it could be removed? Then we will think again what to do with the package — maybe clone from some another branch.

**Expected behavior**
`next` points to the most recent version of the code.

**Comment by rcaelers** [comment]
The `next` branch is not outdated. Compared to `branch_v1_10` it contains a lot of refactoring (code split into small libraries) and code modernization (use of C++14, Boost, cmake). It also contains an initial port to macOS using Qt5. It should not have more functionality compared to `branch_v1_10`. The `next` branch didn't get as much testing as the `branch_v1_10`, so I never dared to do an official release based on the `next` branch. But it will happen eventually. I didn't know the `next` branch was already packaged. 

The last commit to `branch_v1_10` was actually a backport of a `next` change (use of python 3 for dbus code generation instead of python 2). I also regularly merge `branch_v1_10` into `next`.

**Comment by kindaro** [comment]
I don't understand. I just cloned the whole repository anew. This is what I see:

* Default branch:

        % git log --max-count 1 branch_v1_10
        commit 594848e1aa11191d0b5ee2cc3c081ff3ca773977 (HEAD -> branch_v1_10, tag: v1_10_34, origin/branch_v1_10, origin/HEAD)
        Author: Rob Caelers <rob.caelers@gmail.com>
        Date:   Tue Jun 4 20:29:00 2019 +0200

        Release 1.10.34
        
        Signed-off-by: Rob Caelers <rob.caelers@gmail.com>

* `next`:

        % git log --max-count 1 origin/next
        commit 36786eb71e21c09837d5d8961da9977c9502249a (origin/next)
        Author: Rob Caelers <rob.caelers@gmail.com>
        Date:   Sat May 11 13:57:16 2019 +0200

            Make script more consistent with v1.10 version
            
            Signed-off-by: Rob Caelers <rob.caelers@gmail.com>

Looking at the dates, it appears that `next` is behind `branch_v1_10` by 24 days. Could it be that you have local changes that are not pushed to the cloud?

**Comment by rcaelers** [comment]
`branch_v1_10` is the stable branch, `next` is the unstable branch. I occasionally do bug fixes and small improvements in `branch_v1_10`. So sometimes the last commit in `branch_v1_10` is more recent than the one in `next`. Changes to `branch_v1_10` are periodically merged into `next`, but usually not the other way.

In the branches overview you can see that `next` is 651 commits ahead of `branch_v1_10`:

![Screenshot 2019-07-21 at 20 30 58](https://user-images.githubusercontent.com/80881/61595371-94e74600-abf6-11e9-8a50-c770d0e87abc.png)

**Comment by kindaro** [comment]
So those 38 commits that `branch_v1_10` is ahead by will be merged into `next` within some period of time, is that correct?

**Comment by rcaelers** [comment]
Correct:
![Screenshot 2019-07-30 at 00 49 58](https://user-images.githubusercontent.com/80881/62088018-175dae80-b264-11e9-968d-79fb06454cbb.png)
Next branch is again up-to-date.

**Comment by kindaro** [comment]
Thank you.
