### ISSUE TITLE
No Menu in Ubuntu 19.10

### ISSUE THREAD

**Issue by rubo77** [rcaelers/workrave#173]
There is no Menu to reach the settings of Workrave in Ubuntu.

 - Distribution:  Ubuntu
 - Distribution Version: 19.10
 - Desktop Environment: Gnome
 - Workrave Version 1.10.34-2

I want to change the break time. Is there a Workaround to edit some config file or so?

**Comment by Juillermo** [comment]
Same problem here.

- Distribution: Ubuntu
- Distribution Version: 18.04.4 LTS
- Desktop Environment: Gnome 3.28.2
- Workrave Version: 1.10.16-2ubuntu1

**Comment by rcaelers** [comment]
You don't have a white sheep icon in the top status bar? Right clicking on this icon should give you a [menu](https://workrave.org/docs/menus/) to open the preferences. You can also enable the Gnome applet to control Workrave. See: https://workrave.org/docs/applets/gnome/

**Comment by Juillermo** [comment]
I did not have the white sheep icon in the top status bar. The applet extension helped getting it back to place. Thank you!

**Comment by rubo77** [comment]
That worked, you should add the `gnome-tweaks` package to the dependencies of workrave or at least as recommended

**Comment by rcaelers** [comment]
Many desktop environments no longer show status icons. So you indeed have to add the Gnome Shell applet extension and enable it using gnome-tweaks, as described on the Workrave website.

Also, due to a bug, it was possible to close the main (timer) window when no applet or status icon was visible. As a result,  there was indeed no way to access the menu. That bug has been resolved. So I am closing this issue. Please reopen if you still encounter this issue.
