### ISSUE TITLE
Error when installing v1.10.37

### ISSUE THREAD

**Issue by kazerniel** [rcaelers/workrave#176]
**Describe the bug**
When updating from v1.10.34 I get the following error, even when running the exe as administator:

![image](https://user-images.githubusercontent.com/5689996/78263568-0a334680-74fa-11ea-8e88-9aff7f04042e.png)

**To Reproduce**
1. Launch `workrave-win32-v1.10.37`.
2. Click through until it starts extracting files
3. See error

**Windows**
 - Windows Version: Win 7 Pro SP1 x64
 - Workrave Version: 1.10.37

**Comment by rcaelers** [comment]
This was actually a bug in 1.10.34 that was fixed in 1.10.35. I removed code that I though was no longer used. As a result, the installer was no longer able to terminate Workrave. For now you have to terminate Workrave manually.

I have added a workaround in 1.10.39 that will also properly terminate 1.10.34.

**Comment by kazerniel** [comment]
But I did manually close the program on the tray when the installer asked.

**Comment by kazerniel** [comment]
Hi, I tried to install v1.10.41 now, buit I get the same error. I manually closed Workrave before, and it wasn't running as a background process either.

**Comment by rcaelers** [comment]
Neither Workrave.exe and WorkraveHelper.exe show up in the task manager?
If not, can you remove C:\Program Files (x86)\Workrave\lib\libexpat-1.dll ?  
Do you admin rights? Workrave installs keys in the registry for which it needs admin rights, so maybe an only admin can replace the file.

**Comment by kazerniel** [comment]
> Neither Workrave.exe and WorkraveHelper.exe show up in the task manager?

Neither of them were in the task manager at the time of the install.

I have admin rights. When I tried to delete libexpat-1.dll, I got the following error (even when I launched my file manager as admin) :

![image](https://user-images.githubusercontent.com/5689996/78581969-83010e00-782c-11ea-899f-88c959b04654.png)

When I killed that dbus-daemon.exe in the Task Manager, I managed to delete libexpat-1.dll, and run the install without error :+1:

**Comment by rcaelers** [comment]
Support for DBus on Windows was removed several years ago. I am surprised that dbus-daemon is running. It is not longer distributed with Workrave.

**Comment by rcaelers** [comment]
The Workrave installer should terminate Workrave (including dbus-daemon) when updating/uninstalling Workrave. Because of a bug in the installer of 1.10.37 Workrave did not do that. When manually stopping Workrave, dbus-daemon is not stopped. DBUS is no longer supported on Windows (though the installer still kills it, in case you are updating from an old version), so this issue should no longer occur.
