### ISSUE TITLE
Workrave mistakenly launches in German

### ISSUE THREAD

**Issue by xerus2000** [rcaelers/workrave#189]
**Describe the bug**
I have my default system locale set to en_IE and the language to en_US, but Workrave launches in German when launched from the application menu. Weirdly enough, it always launches in English from the command line, even when I launch the .desktop-file via `kiolauncher exec` or `gtk-launch`.

Output of `locale`:
```
LANG=en_IE.UTF-8
LANGUAGE=en_US:en_GB:de
LC_CTYPE=en_IE.UTF-8
LC_NUMERIC="en_IE.UTF-8"
LC_TIME="en_IE.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_IE.UTF-8"
LC_MESSAGES=C
LC_PAPER="en_IE.UTF-8"
LC_NAME="en_IE.UTF-8"
LC_ADDRESS="en_IE.UTF-8"
LC_TELEPHONE="en_IE.UTF-8"
LC_MEASUREMENT="en_IE.UTF-8"
LC_IDENTIFICATION="en_IE.UTF-8"
LC_ALL=
```

**Expected behavior**
Workrave always launches in English.

**System**
OS: KDE neon User Edition 5.18 x86_64 based on Ubuntu bionic 18.04

**Comment by rcaelers** [comment]
Where did you set system locale and language ? in KDE's settings (I'm not familiar with KDE) ? or in login scripts?

When I set the same variables, except LC_MESSAGES, from the command line, I also get German. Do you know where the 'de' in LANGUAGE comes from?

**Comment by xerus2000** [comment]
I set it in KDE's settings, but as said the output is from the terminal and I looked a little into the generating scripts. 

The 'de' is there as a fallback because that is my mother tongue, though I prefer interfaces in English. Yeah, I guess I could remove it, but either way this is unexpected behavior?

**Comment by rcaelers** [comment]
I installed KDE Neon User Edition and tried to replicate this.

After changing the system locale and preferred languages, I get this:

LANG=en_IE.UTF-8
LANGUAGE=en_US:en_GB:de
LC_CTYPE="en_IE.UTF-8"
LC_NUMERIC="en_IE.UTF-8"
LC_TIME="en_IE.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_IE.UTF-8"
**LC_MESSAGES="en_IE.UTF-8"**
LC_PAPER="en_IE.UTF-8"
LC_NAME="en_IE.UTF-8"
LC_ADDRESS="en_IE.UTF-8"
LC_TELEPHONE="en_IE.UTF-8"
LC_MEASUREMENT="en_IE.UTF-8"
LC_IDENTIFICATION="en_IE.UTF-8"
LC_ALL=

In your output LC_MESSAGES is C, Do you know where that comes from? 
According to the documentation, LANGUAGE is ignored if the locale is set to C, so for messages (translations) the LANGUAGE variable is ignored. My guess is that this is only set in your terminal and not when starting from the menu. When I start vlc, I see the same behavior as Workrave. It's in German. Other application (mostly native KDE applications) seem fine... `ls --help` shows both German en English output...

I think Workrave reverts to German because there is no en_US or en_GB translation. When LC_MESSSAGES is set to C, you get the text as defined in the code (which is English).

**Comment by xerus2000** [comment]
Well, I just configured my language like that, C was only supposed to be in LC_COLLATE to have the Linux way of sorting things, idk why it also ends up in LC_MESSAGES.

![image](https://user-images.githubusercontent.com/13354331/81108711-54ed1780-8f19-11ea-8797-4add4a967468.png)

**Comment by xerus2000** [comment]
You are right, vlc behaves the same, interesting...

**Comment by xerus2000** [comment]
I found en_DE in the languages and selected that, workrave launches in english all the time now - interesting...

**Comment by xerus2000** [comment]
But I still don't know why, regardless of which languages I configure, LC_MESSAGES is set to C

**Comment by xerus2000** [comment]
About LC_MESSAGES: Apparently I had an `export LC_MESSAGES=C` line in my own shell config :man_facepalming:

Now that I removed that it works the same both from terminal and command-line: 
If I include "de" in `LANGUAGE`, then workrave and vlc launch in German, if I remove that they launch in English. Still weird though, I even explicitly included plain "en" in my LANGUAGE (so it is `LANGUAGE=en_US:en:de`) but "de" seems to take precedence, at least for gettext, even though it should favor the ones that come first...

**Comment by xerus2000** [comment]
About LC_MESSAGES: Apparently I had an `export LC_MESSAGES=C` line in my own shell config :man_facepalming:

Now that I removed that it works the same both from terminal and command-line: 
If I include "de" in `LANGUAGE`, then workrave and vlc launch in German, if I remove that it launches in English. Still weird though, I even explicitly included plain "en" in my LANGUAGE (so it is `LANGUAGE=en_US:en:de`) but "de" seems to take precedence, at least for gettext, even though it should favor the ones that come first...

**Comment by xerus2000** [comment]
Indeed, `ls` displays the same behavior, I'll experiment a little more...

**Comment by xerus2000** [comment]
It gets even weirder - it actually seems to be related to LC_MESSAGES.
These examples both output English:
```
LC_MESSAGES=en_US.UTF-8 LANGUAGE=en mv --version
LC_MESSAGES=en_US LANGUAGE=en:de mv --version
```
While this results in German output:
```
LC_MESSAGES=en_US.UTF-8 LANGUAGE=en:de mv --version
```
Now this doesn't seem to be about your project, but I have no idea where to report it...

**Comment by xerus2000** [comment]
Okay, found the solution: https://unix.stackexchange.com/questions/181857/the-language-locale-variable-how-to-set-english-as-primary-language-a-bug-i
oof...

**Comment by rcaelers** [comment]
Thanks for sorting this out. This feels like a bug. You expect to get English when you set that as preferred language. Unfortunately, solving this in Workrave would require some hacks that parses and rewrite LANGUAGE and perhaps other variables.... 

Most applications use English as their native "C" language and translate from English to other languages. So having English as default and German as fallback is not very useful, because the fallback will never be used. Unless an application uses French as their "C" language and translates from French to English and German.

I think the main issue is that an application cannot tell the gettext/libintl library which language it uses for the "C" locale.
