### ISSUE TITLE
BUG in counter. Sometimes doesn't respect user inactivity

### ISSUE THREAD

**Issue by jt007** [rcaelers/workrave#228]
Most of the time, the "daily limit" counter run for the preset amount of time after last keystroke/mouse action, before it stops because of inactivity. Unfortunately sometimes it continues to run for hours after last keystroke/mouse action even if it normally stops after 30 sec of inactivity (my settings). 

Because of this I find it hard to trust the counter. Many times it continues to run after those 30 sec of inactivity, and when I come back to computer more than an hour later, it still runs. And when I try to test it (with no change in settings!), it stops after 30 sec of inactivity as "normal" for several tests....

What could be the reason behind this varying behavior? Is this possible to fix to make the counter possible to trust?

**Comment by jt007** [comment]
This bug discovered in version 1.10.44, running on windows 10. Otherwise a great app! :)

**Comment by rcaelers** [comment]
In the preferences, in the timers section, monitoring tab. Could you try to enable the 'Use alternate monitor' checkbox and check if that solves the issue? 

More people have complained about this recently...

**Comment by rcaelers** [comment]
I am closing this issue because it is stale for a couple of months. If you still encounter this issue in Workrave 1.10.45, and switching to the 'alternate monitor' does not the issue, please reopen and the try the following:

When you encounter the problem, open the preferences, and go to the 'Monitoring' tab in the Timers section. Press the 'Debug monitoring' button. A new window should appear that shows some internal state and state changes. Wait a minute or so and copy/paste the content of the debug window and add it to this bug report or mail it to me (there should not be any personal data in the logs)
