### ISSUE TITLE
workrave shows twice in statusbar after running it

### ISSUE THREAD

**Issue by freddii** [rcaelers/workrave#258]
I run workrave from terminal with: 
workrave
Then it show up twice in statusbar.

It should only show up once.

Distribution:
Debian XFCE

workrave version:
1.10.44

![workrave-twice-statusbar](https://user-images.githubusercontent.com/7213207/101072104-cff4da00-359d-11eb-8f2b-1558dde1f2d8.png)

**Comment by rcaelers** [comment]
This will be fixed in 1.10.45. 

The first icon is the standard system tray icon that can be enabled using this 'Show system tray icon' setting:

<img width="543" alt="General settings" src="https://user-images.githubusercontent.com/80881/104852379-178bb700-58fb-11eb-860f-da66374df4d5.png">

At the moment, this setting also enables/disables the status icon in the applet. The second icon you see is from the 'fallback' applet. This applet is truncated on most desktop environments, so you only see the icon.

In the Workrave 1.10.45 you will be able to disable the fallback applet (this is the default) and enable/disable the icon in the applet separately:

<img width="648" alt="Applet settings" src="https://user-images.githubusercontent.com/80881/104852390-1f4b5b80-58fb-11eb-933e-93a712591f0c.png">

For now, you could disable the system tray icon and activate the XFCE applet (https://workrave.org/docs/applets/xfce/). This should (I think) give only one icon.
