### ISSUE TITLE
"Start restbreak when screen is locked" option doesn't work

### ISSUE THREAD

**Issue by HappyRay** [rcaelers/workrave#294]
**Describe the bug**
"Start restbreak when screen is locked" option doesn't work

**To Reproduce**
I enabled the "Start restbreak when screen is locked" option.
Lock the screen or put the computer to sleep 
I expect the micro-break timer to reset. 
It doesn't.
It doesn't matter if I am in reading mode or not.

I remember this feature used to work. But I am not sure which version now.

 - Windows Version: [ Windows 10]
 - Workrave Version 1.10.45

**Comment by rcaelers** [comment]
The purpose of the "Start restbreak when screen is locked" option is not to reset the micro-break timer.
When you lock the screen, and then unlock, Workrave will show a 'natural restbreak' window.
This way you can prevent that your restbreak idle time is reset when you unlock the computer (because you unlock by using keyboard or mouse). 

If your screen was locked for more than the duration of your micro break, the micro break timer should reset. 

Your micro break does not reset if you lock the screen for more than the micro break duration?

**Comment by HappyRay** [comment]
Thanks for the explanation.

> Your micro break does not reset if you lock the screen for more than the micro break duration?
It does.
