### ISSUE TITLE
Applet is not displayed correctly in GNOME top bar on Ubuntu 18.04

### ISSUE THREAD

**Issue by mlemmens** [rcaelers/workrave#323]
**Describe the bug**
I use the applet to show the timers in the GNOME top bar with change between timer every 10 seconds. However, after the recent update to version 1.10.47, this does not work correctly any more. Only the Workrave status icon is visible. When I disable the status icon, only a small part is displayed. The _Fallback applet enabled_ option does not have any effect.

**To Reproduce**
1. In GNOME tweaks enable the Workrave extension.
2. Go to Settings > User Interface
3. On tab Applet enable/disable the status icon.

**Expected behavior**
The applet display correctly in GNOME top bar.

**Screenshots**
![workrave applet bug 1](https://user-images.githubusercontent.com/15130187/127897784-5d149818-5389-4631-8bfd-eea0b6706519.png)
![workrave applet bug 2](https://user-images.githubusercontent.com/15130187/127897781-15dfd21c-ece5-4aa8-aafb-2aa0e9851778.png)
(Most of the settings are in Dutch language)

**Linux**
 - Distribution: Ubuntu 
 - Distribution Version: 18.04.5
 - Desktop Environment: GNOME Shell 3.28.4
 - Workrave Version: 1.10.47

**Comment by rcaelers** [comment]
Thanks for reporting. This bug should be fixed in 1.10.48.

**Comment by kbulygin** [comment]
I had the same issue on MATE after upgrading from Debian 10 to 11 (bullseye), even with 1.10.48 (built manually using deps from https://hub.docker.com/layers/rcaelers/workrave-build/debian-testing/images/sha256-3066b1a35f434f9d024df3167e118df4046fdce1fc12f79b57eb580d84839b3e?context=explore) and even on a fresh Debian 11 installation with Cinnamon and Workrave 1.10.44 (from the repo) after using the system for a while. It turned out that sometimes when other applets are added, Workrave Applet gets collapsed (only the icon for the current timer is visible) and expands when it switches to another timer. But when only one timer is enabled, this redrawing never happens. So a workaround is to temporarily enable another timer.
