### ISSUE TITLE
[Feature request] "Start break" button on "Prompt" window

### ISSUE THREAD

**Issue by skeets23** [rcaelers/workrave#376]
I like using the "prompt" window so that I'm not interrupted unexpectedly by a micro-break.
However, it's really distracting that I'm unable to start the break when I'm ready... I have to stop touching the mouse and keyboard for long enough for the break to "start".

This would be solved quite nicely with a "Start break" button.

**Comment by kees-jan** [comment]
Thing is, if you try to click on the prelude window (as we call the "prompt" window), you'll notice that it jumps away. So if we placed a button on there, you wouldn't ever be able to click it. The "jumping away" is there intentionally, to make it easy for you to continue working (if you so choose): You can start typing, and if the break window is in your way, it'll move as soon as the mouse approaches is.

So adding a button there has some consequences. And I'm not exactly sure it is the way to go.

Thing is, stopping to touch the mouse and keyboard is quite a sensible thing to do, if your intention is to take a break 😝. And your statement that you have to wait for the break to start isn't exactly true. You have to wait for the break window to appear. But, if you stop touching mouse and keyboard within 1 second after the prelude appearing, then that waiting time counts towards your break time (even if the break window isn't visible yet). If you open the workrave status window, or are using the applet, you'll see the green bar increasing.

So, if speed is of the essence (as your text seems to suggest), then stopping to touch mouse and keyboard immediately when the prelude appears, is the fastest way to your break being over 😉.

**Comment by skeets23** [comment]
Hmmm, yeah maybe I hadn't really thought out the button thing. I guess that wouldn't work...

> if you stop touching mouse and keyboard within 1 second after the prelude appearing, then that waiting time counts towards your break time

Ok, I'd been wondering about this, because I had noticed that the waiting during the prelude time counted towards my microbreak timer... but only rarely. Knowing the conditions for this to happen helps, but only a tiny bit, because following those conditions make the prelude useless... if I was ready to take a break with literally less than one second of warning, I wouldn't really need a prelude, would I?

My understanding of the prelude feature is: I'm not ready to take a break at any given spontaneous moment, but given a 30 second warning, I can finish typing the line I was working on / finish reading the paragraph I was reading / etc. and then start my break.

And this works great, except I find it strange that waiting during the prelude screen counts if you start within one second, and not if you actually use the prelude for it's intended purpose (getting to a slightly better stopping point before taking the break). It almost feels like I'm being "penalized" by 10 seconds.

Yeah I realize 10 seconds isn't the end of the world, but when it's a minor annoyance that happens 24 times a day (I have microbreaks scheduled very frequently to give my eyes plenty of breaks), it can get frustrating. My microbreaks are very short to start with (20 seconds), so adding 10 seconds is quite a bit.

However, now that I know the criteria, I suppose I have my workaround: shorten my microbreak length by 10 seconds in the settings, and then when the prelude window comes up just make sure I *don't* stop touching mouse or keyboard for the first one second to make sure I still get the full 20 second break.

It would be nice to have more options for the prelude window though. (2 things I would like most is 1. add option to *always* include the 10 second wait from the prelude in the micro-break and 2. allow the user to change the length of the prelude (sometimes the 30 seconds isn't enough.... if I could I'd raise it to 60 seconds, which would probably increase my chances of actually taking a break when I intended to.))

**Comment by kees-jan** [comment]
The 10 seconds you mention is actually 5 seconds, if memory serves.

You're now touching upon the algorithm used by workrave to know that you are active. Workrave either considers you active or inactive. 

- When it considers you active, you have to stop working for 5 seconds, and then it'll consider you inactive.
- When it considers you active, you have to generate 2 "events" (key presses, mouse moves, button clicks) with 1s between them, and then it'll consider you active.

The system is not perfect. If workrave considers you inactive, then you could work frantically for 1s and then take a 5s break and then repeat, and workrave wouldn't ever consider you active. On the other hand, if you stop working, it takes workrave 5s to notice.

Like I said, the system is not perfect, but it seems good enough for most people, and it is hard to improve it, without also breaking stuff for others.

There's one more thing: If the prelude window appears, workrave considers you active immediately. That's why the waiting time counts towards your break time. That's also where the 1s comes from: It is the normal time for workrave to consider you active again, if you're currently inactive.

Regarding you needing 33s to reach a "natural" stopping point before taking a break: If you would just stop working at that point (in spite of there not being a prelude any more), it would take workrave 5s to notice you're inactive (as usual), and everything after that counts towards your break time. So after a total of 25s, your break would be over (in spite of no windows popping up at all). We call this a natural break.

Truth be told, I find the prelude windows kind of annoying, so if I decide to continue working, I'm happy to see them go after 30s. I would not be in favor of extending that time. And then, If I decide to break anyway, I can just stop working and sit out my 25 seconds. I always have an applet open to monitor workraves current state.

**Comment by skeets23** [comment]
> The 10 seconds you mention is actually 5 seconds, if memory serves.

Huh, it looks like you're right. I must have measured it when releasing from keyboard & mouse instantly and assumed it was the same. Here's what I measured just now:

Stop touching keyboard and mouse after the prompt window gets to "27": Takes 5 seconds to start the break
Stop touching keyboard and mouse before the prompt window gets to "28": Takes 9 seconds to start the break (and those 9 seconds are counted as part of the break, so technically the break starts immediately)

It's a little strange that it takes *longer* for the prompt window to go away and the break window to appear in the second example above... that sounds like unintended behavior. Not that it's a huge deal since the chances of actually being able to start a break with less than a second's notice is pretty slim 😅

I guess if it's such a big deal, I can just adjust my break time down 5 seconds to account for the inactivity detection and stop complaining. Workrave has done wonders for my eyes... I used to get blood shot eyes all the time.

I also came up with a partial work-around for not being able to adjust the prompt window length -- I can set the "postpone" length to "1 second", and that basically makes it a never-ending prompt window forcing me to take a break so it will go away. Some days I need that to avoid killing my eyes when I'm overly focused on what I'm working on 😛

Anyway, thanks for explaining some of the inner workings to a random complainer. And thank you for your contributions to this awesome software.
