### ISSUE TITLE
Customize exercise set

### ISSUE THREAD

**Issue by nawordar** [rcaelers/workrave#509]
My doctor has prescribed me a set of exercises. I would like to have the ability, to remove the built-in exercises and add the one recommended by the practitioner instead.
Each exercise would have the following properties:
1. An image or animation accompanying each stage of exercise (pause, stretch)
2. Duration of each stage
3. Number of repetitions

**Comment by JudithvW** [comment]
Within the installation folder (usually C:\Program Files (x86)\Workrave) there is a folder named share and inside a folder named exercises. Within this exercises folder, you can add the images you want for your prescribed exercises. Then adjust the exercises.xml file to remove the default exercises and add your own. With the use of the duration, you can provide the duration for the whole set and the duration for each action.

So for example, the head turn exercise. Looking left takes 3 seconds. Looking right takes 3 seconds. The whole set has a duration of 24 seconds. So that means that you do 4 repetitions.

You can leave out all the other languages, so every exercise only needs a single title and a single description.

**Comment by igorsantos07** [comment]
For those trying to do the same but don't use :window:s, look for that under `/usr/share/workrave/exercises` :)
