### ISSUE TITLE
Version uploaded to SourceForge is very out of date

### ISSUE THREAD

**Issue by enolan** [rcaelers/workrave#96]
[The newest version on SF is 1.10.1](https://sourceforge.net/projects/workrave/files/workrave/), while GitHub has releases up to 1.10.20.

**Comment by PatrickCVD** [comment]
Yes we also would like a compiled Windows version of the latest release since we still use 1.10.1 and sometimes Workrave crashes leaving no error report so we hope the latest version has fixed this issue.

![naamloos](https://user-images.githubusercontent.com/36485520/37895941-367c6500-30d2-11e8-9441-96d49e1f63ab.png)

**Comment by klonamy** [comment]
Is there an update on this issue?

**Comment by rcaelers** [comment]
Workrave is now automatically published on Github when a new release is made. Website will be updated at a later time. 1.10.21 is available for download on Github

**Comment by johnypowa** [comment]
Hello,

You did for sure thought about closing the account on sourceforge, or at least put a message there inviting the user to go to workrave.org or on github, right?

I didn't knew at all that workrave moved to github :-(
(since years, I thought the project was dead/zombie ...)

And this, because if you type "workrave" on google.com you don't find either workrave.org nor the github page (at least from switzerland).

Please fix this. Thank you very much for your work!
